# Generated by Django 5.0.2 on 2025-10-05 09:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="length",
            field=models.CharField(default="medium", max_length=20),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="tone",
            field=models.CharField(default="professional", max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name="blogpost",
            unique_together={("user", "youtube_link", "tone", "length")},
        ),
    ]
